#pragma once
#include "changeColor/changeColor.h"
#include "checkDir/checkDir.h"
#include "checkEmptyFile/checkEmptyFile.h"
#include "compile/compile.h"
#include "numberOfFiles/numberOfFiles.h"
#include "showPath/showPath.h"
#include "copyFile/copyfile.h"
#include "errorHandeling/errorHandeling.h"
